server:
  port: 8801

spring:
  application:
    name: rabbitmq-unittest
  rabbitmq:
    host: "10.2.3.250"
    port: 5672
    username: admin
    password: "admin"

# RabbitMQ直接mock，会忽略配置，因此不需要设置 profiles
