server:
  port: 8801

spring:
  application:
    name: gitlab-operation
  profiles:
    active: dev
logging:
  level:
    beinet.cn.demogitlaboperation.feign: DEBUG

---  # 2个三横杠之间表示一个环境配置
spring:
  profiles: unittest # 单元测试，通过注解 ActiveProfiles 使用这一段

---
spring:
  profiles: dev # 开发使用这一段

gitlab:
  host: https://code.beinet.cn
  token: "123456" #gitlab里用户设置下，申请的访问令牌
---
