
server:
  port: 8801

spring:
  application:
    name: mongo-unittest
  profiles:
    active: dev

---  # 2个三横杠之间表示一个环境配置
spring:
  profiles: unittest # 单元测试，通过注解 ActiveProfiles 使用这一段

---
spring:
  profiles: dev # 开发使用这一段
  data:
    mongodb:
      host: 10.2.3.250
      port: 27017
      username: beinet
      password: beinet123
      database: firstdemo
---
