server:
  port: 8801

spring:
  application:
    name: feign-unittest
  profiles:
    active: dev

logging:
  level:
    beinet.cn.demounittestfeign.FeignBaidu: debug # 这是你的FeignClient的完整类名

feign:
  client:
    config:
      default:
        loggerLevel: full

---  # 2个三横杠之间表示一个环境配置
spring:
  profiles: unittest # 单元测试，通过注解 ActiveProfiles 使用
---
spring:
  profiles: dev # 开发使用这一段
---